GET http://localhost:8000/api/user/tips
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE2MTIzODgxNjcsInN1YiI6InRlc3QifQ.0lxcVOfOgV5K9J6JCzYqns3mey12ksatLSaf2--EwIM
###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "user_name": "test",
    "user_password": "thisismypass123!"
}